name = "Simple problem"
version = "1.0"

# 0 = valid, 1 = invlid (boundary)
# Only need to enter 0 for spacings
# Use ';' for a newline

board = '''
1
01
000001
000011
'''

pieces = [
    "1;11", "1111", "1111;001", "11;1", "111;01"
    ]