name = "Simple searching problem"
desc = "Simple problem with some variability for perturbations"
version = 1.0

# 0 = valid
# 1 = invalid
# ? = optional
board = '''
1000??
00?000
00000?
11?0??
11?0??
'''

pieces = [
    "1;11", "1;111", "1111", "01;111"
]